// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXvf3Pn6UCC3SXjGphkT41EY50j54XDho',
    appId: '1:547810480733:web:146681fbd9d5adfddd73b4',
    messagingSenderId: '547810480733',
    projectId: 'keys-edeaa',
    authDomain: 'keys-edeaa.firebaseapp.com',
    storageBucket: 'keys-edeaa.firebasestorage.app',
    measurementId: 'G-T4VR14K9W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzyKHyB5I9ivKH0lNQAAljcCCySj__LfE',
    appId: '1:547810480733:android:083ff1a1254dc9dfdd73b4',
    messagingSenderId: '547810480733',
    projectId: 'keys-edeaa',
    storageBucket: 'keys-edeaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANU6ycpZEIXQOB69tu0lI9YClRHDCkbXg',
    appId: '1:547810480733:ios:8b28e116a0323008dd73b4',
    messagingSenderId: '547810480733',
    projectId: 'keys-edeaa',
    storageBucket: 'keys-edeaa.firebasestorage.app',
    androidClientId: '547810480733-s2hmfis8gc451knuaj09iikbrlnj8s08.apps.googleusercontent.com',
    iosClientId: '547810480733-59ofjdv2qtslu81cgfqld882b8tgr6l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANU6ycpZEIXQOB69tu0lI9YClRHDCkbXg',
    appId: '1:547810480733:ios:8b28e116a0323008dd73b4',
    messagingSenderId: '547810480733',
    projectId: 'keys-edeaa',
    storageBucket: 'keys-edeaa.firebasestorage.app',
    androidClientId: '547810480733-s2hmfis8gc451knuaj09iikbrlnj8s08.apps.googleusercontent.com',
    iosClientId: '547810480733-59ofjdv2qtslu81cgfqld882b8tgr6l7.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXvf3Pn6UCC3SXjGphkT41EY50j54XDho',
    appId: '1:547810480733:web:61dfad473794a9aedd73b4',
    messagingSenderId: '547810480733',
    projectId: 'keys-edeaa',
    authDomain: 'keys-edeaa.firebaseapp.com',
    storageBucket: 'keys-edeaa.firebasestorage.app',
    measurementId: 'G-FZQY1THZ0C',
  );

}